"project_id": 650126
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "/po/Airpod-Battery-Monitor.pot",
    "translation": "/po/%two_letters_code%.po",
    "ignore": [
      "/**/%locale_with_underscore%",
    ]
  },
  {
    "source": "/po/Airpod-Battery-Monitor.pot",
    "translation": "/po/%locale_with_underscore%.po",
    "ignore": [
      "/**/%two_letters_code%.po",
    ]
  }
]
